services:
  petcast:
    image: ghcr.io/kylekampy/petcasts:latest
    container_name: petcast
    ports:
      - "7777:7777"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - /opt/volumes/petcast/state:/app/pets/state
      - /opt/volumes/petcast/output:/app/output
    restart: unless-stopped
